"""
VayuGrid Incident & Ticketing Pydantic Data Models
Defines schemas for incident lifecycle state machine, ingestion payloads (multipart & base64),
statutory municipal dispatch work orders, and incident persistence records.
"""

from enum import Enum
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class IncidentStatusEnum(str, Enum):
    """Statutory Incident Lifecycle States."""
    REPORTED = "REPORTED"                # Edge ingestion received, awaiting audit
    PENDING_AUDIT = "PENDING_AUDIT"      # Queue assigned, forensic audit executing
    VERIFIED_HAZARD = "VERIFIED_HAZARD"  # Audited, physical dispersion calculated
    DISPATCHED = "DISPATCHED"            # Municipal mitigation unit en route
    RESOLVED = "RESOLVED"                # Hazard mitigated / dissipated, closed
    REJECTED_SPOOF = "REJECTED_SPOOF"    # Anti-spoofing rejected / non-hazard


# Valid lifecycle state transitions
VALID_STATE_TRANSITIONS: Dict[IncidentStatusEnum, List[IncidentStatusEnum]] = {
    IncidentStatusEnum.REPORTED: [
        IncidentStatusEnum.PENDING_AUDIT,
        IncidentStatusEnum.VERIFIED_HAZARD,
        IncidentStatusEnum.REJECTED_SPOOF,
    ],
    IncidentStatusEnum.PENDING_AUDIT: [
        IncidentStatusEnum.VERIFIED_HAZARD,
        IncidentStatusEnum.REJECTED_SPOOF,
    ],
    IncidentStatusEnum.VERIFIED_HAZARD: [
        IncidentStatusEnum.DISPATCHED,
        IncidentStatusEnum.RESOLVED,
    ],
    IncidentStatusEnum.DISPATCHED: [
        IncidentStatusEnum.RESOLVED,
    ],
    IncidentStatusEnum.RESOLVED: [],  # Terminal state
    IncidentStatusEnum.REJECTED_SPOOF: [],  # Terminal state
}


class CoordinatesModel(BaseModel):
    """Geographic coordinates of the reported incident."""
    latitude: float = Field(..., ge=-90.0, le=90.0, description="Latitude in decimal degrees")
    longitude: float = Field(..., ge=-180.0, le=180.0, description="Longitude in decimal degrees")
    address_hint: Optional[str] = Field(None, description="Human-readable landmark or address")


class IncidentVerificationDetails(BaseModel):
    """AI Forensic verification details generated by Gemini."""
    is_valid_environmental_hazard: bool = Field(..., description="True if real outdoor pollution")
    rejection_reason: Optional[str] = Field(None, description="Reason if rejected as spoof")
    source_classification: str = Field(..., description="Classification category")
    severity_score: float = Field(..., ge=0.0, le=1.0, description="Severity score 0.0 to 1.0")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Model confidence 0.0 to 1.0")
    optical_smoke_opacity: float = Field(0.0, ge=0.0, le=1.0, description="Optical opacity")
    estimated_plume_spread_radius_meters: int = Field(25, ge=0, description="Plume radius in meters")
    detected_visual_markers: List[str] = Field(default_factory=list, description="Forensic markers")
    recommended_ulb_action: Optional[Dict[str, Any]] = Field(None, description="Action suggestion")
    summary_assessment: Optional[str] = Field(None, description="Commissioner summary")


class MeteorologySummary(BaseModel):
    """Snapshot of meteorological conditions during incident audit."""
    wind_speed_kmh: float = Field(..., description="Wind speed at 10m in km/h")
    wind_speed_ms: Optional[float] = Field(None, description="Wind speed in m/s")
    wind_direction_deg: float = Field(..., description="Meteorological wind direction degrees")
    downwind_bearing_deg: Optional[float] = Field(None, description="Downwind advection bearing")
    temperature_c: float = Field(..., description="Ambient temperature in Celsius")
    humidity_pct: float = Field(..., description="Relative humidity percentage")
    planetary_boundary_layer_height_m: float = Field(..., description="Boundary layer mixing lid")
    stability_class: str = Field(..., description="Pasquill-Gifford stability class (A-F)")


class MunicipalActionRequest(BaseModel):
    """Payload for deploying municipal mitigation assets."""
    action_type: str = Field(
        ...,
        description="Action type: DISPATCH_SMOG_GUN, WATER_SPRINKLER, PATROL_INSPECTION, SECTION_133_NOTICE"
    )
    assigned_unit: str = Field(..., description="Identifier of the field asset or vehicle")
    operator_notes: str = Field(..., description="Field operational instructions")
    officer_badge_id: str = Field(..., description="Statutory ULB officer identification")


class MunicipalActionResponse(BaseModel):
    """Response confirmation after asset dispatch."""
    ticket_id: str
    status: str
    action_timestamp: str
    eta_minutes: int
    confirmation_code: str


class ResolveIncidentRequest(BaseModel):
    """Payload to close an incident upon mitigation completion."""
    officer_badge_id: str = Field(..., description="ULB officer badge authorizing resolution")
    resolution_notes: str = Field(..., description="Notes regarding containment and cleanup")
    mitigation_summary: Optional[str] = Field(
        None,
        description="Mitigation actions applied (e.g., '12,000L water mist suppressed smolder')"
    )


class ResolveIncidentResponse(BaseModel):
    """Response confirmation after resolving an incident."""
    ticket_id: str
    status: str
    resolved_at: str
    message: str


class Base64AuditRequest(BaseModel):
    """Payload for auditing via Base64 JSON."""
    image_base64: Optional[str] = Field(None, description="Base64-encoded image string")
    latitude: float = Field(..., ge=-90.0, le=90.0)
    longitude: float = Field(..., ge=-180.0, le=180.0)
    city_id: Optional[str] = Field(None, description="City archetype identifier")
    reported_by: Optional[str] = Field("FIELD_TELEMETRY", description="Reporting entity")
    compass_heading_deg: Optional[float] = Field(None, ge=0.0, le=360.0)


class IncidentRecord(BaseModel):
    """Comprehensive statutory incident record tracked across the system."""
    ticket_id: str = Field(..., description="Statutory unique ticket identifier")
    status: IncidentStatusEnum = Field(..., description="Current lifecycle state")
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    reported_by: str = Field(default="FIELD_TELEMETRY")
    city_id: Optional[str] = Field(None)
    coordinates: CoordinatesModel
    verification: IncidentVerificationDetails
    meteorology: Optional[MeteorologySummary] = None
    downwind_exposure_cone: Optional[Dict[str, Any]] = None
    physics_simulation: Optional[Dict[str, Any]] = None
    impacted_infrastructure: List[Dict[str, Any]] = Field(default_factory=list)
    vernacular_advisories: Optional[Dict[str, str]] = None
    dispatch_details: Optional[Dict[str, Any]] = None
    resolution_details: Optional[Dict[str, Any]] = None
    image_url: Optional[str] = None
