export const CITIES = [
  {
    id: 'delhi',
    name: 'Delhi-NCR',
    state: 'National Capital Region',
    archetype: 'Polycentric Megacity / Regional Stubble & Dust Corridor',
    center: { lat: 28.6139, lng: 77.2090 },
    zoom: 12,
    cpcb_stations_count: 40,
    current_aqi: 342,
    category: 'VERY_POOR',
    primary_pollutant: 'PM2.5',
    active_incidents: 8,
  },
  {
    id: 'kanpur',
    name: 'Kanpur',
    state: 'Uttar Pradesh',
    archetype: 'Gangetic Basin / Thermal Inversion & Tannery Industrial Belt',
    center: { lat: 26.4499, lng: 80.3319 },
    zoom: 12,
    cpcb_stations_count: 8,
    current_aqi: 389,
    category: 'VERY_POOR',
    primary_pollutant: 'PM2.5 / Cr-VI',
    active_incidents: 5,
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    archetype: 'Peninsular Ridge / Tech Corridor Vehicular Micro-Basin',
    center: { lat: 12.9716, lng: 77.5946 },
    zoom: 12,
    cpcb_stations_count: 12,
    current_aqi: 118,
    category: 'MODERATE',
    primary_pollutant: 'PM10 / NO2',
    active_incidents: 3,
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    archetype: 'Semi-Arid Industrial / Textile & Petrochemical Corridor',
    center: { lat: 23.0225, lng: 72.5714 },
    zoom: 12,
    cpcb_stations_count: 10,
    current_aqi: 245,
    category: 'POOR',
    primary_pollutant: 'PM10 / SO2',
    active_incidents: 4,
  },
  {
    id: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    archetype: 'Coastal Estuarine Delta / High Humidity Winter Inversion',
    center: { lat: 22.5726, lng: 88.3639 },
    zoom: 12,
    cpcb_stations_count: 9,
    current_aqi: 278,
    category: 'POOR',
    primary_pollutant: 'PM2.5',
    active_incidents: 6,
  },
];

export const DEFAULT_CITY = CITIES[0];

export { getAqiTier } from './classifications';
