export const CITIES = [
  {
    id: 'delhi',
    name: 'Delhi-NCR',
    state: 'National Capital Region',
    archetype: 'Polycentric Megacity / Regional Stubble & Dust Corridor',
    center: { lat: 28.6139, lng: 77.2090 },
    zoom: 12,
    cpcb_stations_count: 40,
    current_aqi: 342,
    category: 'VERY_POOR',
    primary_pollutant: 'PM2.5',
    active_incidents: 8,
  },
  {
    id: 'kanpur',
    name: 'Kanpur',
    state: 'Uttar Pradesh',
    archetype: 'Gangetic Basin / Thermal Inversion & Tannery Industrial Belt',
    center: { lat: 26.4499, lng: 80.3319 },
    zoom: 12,
    cpcb_stations_count: 8,
    current_aqi: 389,
    category: 'VERY_POOR',
    primary_pollutant: 'PM2.5 / Cr-VI',
    active_incidents: 5,
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    archetype: 'Peninsular Ridge / Tech Corridor Vehicular Micro-Basin',
    center: { lat: 12.9716, lng: 77.5946 },
    zoom: 12,
    cpcb_stations_count: 12,
    current_aqi: 118,
    category: 'MODERATE',
    primary_pollutant: 'PM10 / NO2',
    active_incidents: 3,
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    archetype: 'Semi-Arid Industrial / Textile & Petrochemical Corridor',
    center: { lat: 23.0225, lng: 72.5714 },
    zoom: 12,
    cpcb_stations_count: 10,
    current_aqi: 245,
    category: 'POOR',
    primary_pollutant: 'PM10 / SO2',
    active_incidents: 4,
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    archetype: 'Coastal Megacity / Land-Sea Breeze Trapping & Construction Corridor',
    center: { lat: 19.0760, lng: 72.8777 },
    zoom: 12,
    cpcb_stations_count: 24,
    current_aqi: 165,
    category: 'MODERATE',
    primary_pollutant: 'PM2.5 / PM10',
    active_incidents: 4,
  },
  {
    id: 'punjab',
    name: 'Punjab Agrarian Belt',
    state: 'Punjab (Ludhiana/Sangrur)',
    archetype: 'Post-Harvest Biomass Burning & Regional Boundary Inversion',
    center: { lat: 30.9010, lng: 75.8573 },
    zoom: 11,
    cpcb_stations_count: 14,
    current_aqi: 412,
    category: 'SEVERE',
    primary_pollutant: 'PM2.5 / Black Carbon',
    active_incidents: 9,
  },
];

export const DEFAULT_CITY = CITIES[0];

export { getAqiTier } from './classifications';
