/**
 * VayuGrid High-Fidelity Mock Telemetry & Incident Datasets
 * Guaranteed fallbacks ensuring zero frontend crashes if backend services are offline.
 */

export const MOCK_INCIDENT_DELHI = {
  ticket_id: 'VAYU-2026-0930-DL-0881',
  timestamp: '2026-09-30T09:18:42Z',
  city_id: 'delhi',
  status: 'PENDING_DISPATCH',
  classification: 'OPEN_MUNICIPAL_WASTE_BURNING',
  statutory_code: 'SRC-01',
  severity_score: 0.88,
  confidence: 0.94,
  location: {
    lat: 28.6289,
    lng: 77.2065,
    address_hint: 'Bhalaswa Landfill Fringe / Sector 16 Peripheral Belt, Outer Ring Rd',
    ward_no: 'Ward 18-N',
  },
  reported_by: {
    persona: 'CITIZEN_FORENSIC_INGEST',
    hash_id: 'USR-899120',
  },
  weather_context: {
    wind_bearing_deg: 45,
    wind_direction: 'NE',
    wind_speed_mps: 4.8,
    ambient_temp_c: 29.4,
    atmospheric_stability: 'Class D (Neutral / Moderate Inversion)',
  },
  downwind_exposure_cone: {
    origin: { lat: 28.6289, lng: 77.2065 },
    wind_bearing_deg: 45,
    wind_speed_mps: 4.8,
    dispersion_rate_mps: 2.1,
    cone_angle_deg: 32,
    max_reach_meters: 3200,
    boundary_polygon: [
      { lat: 28.6289, lng: 77.2065 },
      { lat: 28.6432, lng: 77.2285 },
      { lat: 28.6485, lng: 77.2210 },
      { lat: 28.6360, lng: 77.2010 },
      { lat: 28.6289, lng: 77.2065 },
    ],
  },
  impacted_infrastructure: [
    {
      id: 'INFRA-01',
      name: 'Sarvodaya Kanya Vidyalaya (Govt High School)',
      type: 'SCHOOL',
      lat: 28.6385,
      lng: 77.2180,
      distance_meters: 1420,
      eta_minutes: 11,
      children_count: 850,
      alert_status: 'DISPERSION_BREACH_IMMUTABLE',
    },
    {
      id: 'INFRA-02',
      name: 'North Delhi Community Health Centre',
      type: 'HOSPITAL',
      lat: 28.6420,
      lng: 77.2240,
      distance_meters: 2150,
      eta_minutes: 16,
      capacity_beds: 120,
      alert_status: 'ELEVATED_RISK',
    },
    {
      id: 'INFRA-03',
      name: 'Rohini Metro Transit Terminal',
      type: 'TRANSIT',
      lat: 28.6340,
      lng: 77.2120,
      distance_meters: 890,
      eta_minutes: 7,
      footfall_per_hour: 4200,
      alert_status: 'IMMEDIATE_EXPOSURE',
    },
  ],
  mitigation_options: [
    {
      action_id: 'ACTION-SMOG-GUN',
      label: 'Deploy Anti-Smog Water Cannon Unit 04',
      type: 'SMOG_GUN',
      depot: 'Civil Lines Municipal Fleet Depot',
      response_eta_minutes: 12,
      efficacy_rating: '88% PM10/PM2.5 Plume Quenching',
    },
    {
      action_id: 'ACTION-NOTICE',
      label: 'Issue Automated CAQM Section 31A Show-Cause Notice',
      type: 'ISSUE_NOTICE',
      depot: 'Delhi Pollution Control Committee (DPCC) Legal Desk',
      response_eta_minutes: 0,
      efficacy_rating: 'Immediate Legal Sanction & Penalty',
    },
  ],
  visual_markers: [
    'Dense Black Carbon Particulate Plume (>80% Opacity)',
    'Chlorinated PVC & Polymer Pyrolysis Indicators Detected',
    'Open Uncontained Municipal Heap (Estimated 4.2 Tons Fuel Bed)',
  ],
  vernacular_advisories: {
    en: 'URGENT HEALTH ADVISORY: Dense toxic smoke detected near Bhalaswa perimeter. Avoid outdoor exertion within 2.5 km downwind. Vulnerable groups must remain indoors with air filtration.',
    hi: 'अति आवश्यक स्वास्थ्य चेतावनी: भलस्वा क्षेत्र के समीप अत्यधिक विषैला धुआं दर्ज किया गया है। 2.5 किमी के दायरे में बाहरी गतिविधियों से बचें। बच्चे व वृद्ध घर के भीतर रहें।',
    te: 'ముఖ్యమైన ఆరోగ్య హెచ్చరిక: భలస్వా సమీపంలో విషపూరితమైన పొగ గుర్తించబడింది. 2.5 కి.మీ పరిధిలో బయట తిరగడం మానుకోండి. చిన్నారులు, వృద్ధులు ఇళ్లలోనే ఉండండి.',
    kn: 'ತುರ್ತು ಆರೋಗ್ಯ ಎಚ್ಚರಿಕೆ: ಭಲಸ್ವಾ ಬಳಿ ದಟ್ಟ ವಿಷಕಾರಿ ಹೊಗೆ ಪತ್ತೆಯಾಗಿದೆ. 2.5 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಹೊರಾಂಗಣ ಚಟುವಟಿಕೆಗಳನ್ನು ತಪ್ಪಿಸಿ. ಮಕ್ಕಳು ಮತ್ತು ವೃದ್ಧರು ಮನೆಯೊಳಗೆ ಇರಬೇಕು.',
    ta: 'அவசர சுகாதார எச்சரிக்கை: பலாஸ்வா அருகே அடர்ந்த நச்சுப் புகை கண்டறியப்பட்டுள்ளது. 2.5 கி.மீ சுற்றளவில் வெளியில் செல்வதைத் தவிர்க்கவும். முதியவர்களும் குழந்தைகளும் வீட்டிலேயே இருக்கவும்.',
    ml: 'അടിയന്തര ആരോഗ്യ മുന്നറിയിപ്പ്: ഭലാസ്വയ്ക്ക് സമീപം കനത്ത വിഷപ്പുക കണ്ടെത്തി. 2.5 കി.മീ പരിധിയിൽ പുറത്തിറങ്ങുന്നത് ഒഴിവാക്കുക. കുട്ടികളും മുതിർന്നവരും വീടുകളിൽ തന്നെ തുടരുക.',
  },
};

export const MOCK_INCIDENTS_ALL = [
  MOCK_INCIDENT_DELHI,
  {
    ticket_id: 'VAYU-2026-0930-DL-0882',
    timestamp: '2026-09-30T09:42:15Z',
    city_id: 'delhi',
    status: 'IN_TRANSIT',
    classification: 'CONSTRUCTION_DEMOLITION_DUST',
    statutory_code: 'SRC-02',
    severity_score: 0.67,
    confidence: 0.91,
    location: {
      lat: 28.5720,
      lng: 77.2150,
      address_hint: 'Pragati Maidan Tunnel Expansion Site, C&D Zone 4',
      ward_no: 'Ward 42-S',
    },
    reported_by: {
      persona: 'CONTINUOUS_IOT_ANOMALY',
      hash_id: 'CPCB-STN-29',
    },
    weather_context: {
      wind_bearing_deg: 60,
      wind_direction: 'ENE',
      wind_speed_mps: 3.2,
      ambient_temp_c: 30.1,
      atmospheric_stability: 'Class C (Slightly Unstable)',
    },
    downwind_exposure_cone: {
      origin: { lat: 28.5720, lng: 77.2150 },
      wind_bearing_deg: 60,
      wind_speed_mps: 3.2,
      dispersion_rate_mps: 1.6,
      cone_angle_deg: 28,
      max_reach_meters: 1800,
      boundary_polygon: [
        { lat: 28.5720, lng: 77.2150 },
        { lat: 28.5810, lng: 77.2310 },
        { lat: 28.5860, lng: 77.2270 },
        { lat: 28.5770, lng: 77.2110 },
        { lat: 28.5720, lng: 77.2150 },
      ],
    },
    impacted_infrastructure: [
      {
        id: 'INFRA-04',
        name: 'Delhi Public Library Mathura Road Branch',
        type: 'COMMUNITY',
        lat: 28.5780,
        lng: 77.2240,
        distance_meters: 980,
        eta_minutes: 8,
        alert_status: 'PARTICULATE_SPIKE',
      },
    ],
    mitigation_options: [
      {
        action_id: 'ACTION-MIST',
        label: 'Activate Fixed Fog Cannons & Geo-fenced Stop-Work Order',
        type: 'SMOG_GUN',
        depot: 'South Delhi Municipal Corporation Yard',
        response_eta_minutes: 8,
        efficacy_rating: '76% Fugitive Dust Suppression',
      },
    ],
    visual_markers: [
      'Uncovered aggregate storage pile (>15m height)',
      'Dry aggregate mechanical cutting without localized wetting',
      'Absent green-mesh particulate boundary screening',
    ],
    vernacular_advisories: {
      en: 'Fugitive dust plume detected near Mathura Road corridor. High PM10 concentration. Commuters advised to wear N95 filtration masks.',
      hi: 'मथुरा रोड कॉरिडोर के पास भारी निर्माण धूल दर्ज की गई है। PM10 स्तर अत्यधिक है। यात्रियों को N95 मास्क पहनने की सलाह दी जाती है।',
      te: 'మధుర రోడ్డు సమీపంలో అధిక ధూళి కాలుష్యం ఉంది. ప్రయాణికులు N95 మాస్కులు ధరించాలని సూచన.',
      kn: 'ಮಥುರಾ ರಸ್ತೆ ಕಾರಿಡಾರ್ ಬಳಿ ಧೂಳಿನ ತೀವ್ರತೆ ಹೆಚ್ಚಾಗಿದೆ. ಪ್ರಯಾಣಿಕರು N95 ಮಾಸ್ಕ್ ಧರಿಸಲು ಸೂಚಿಸಲಾಗಿದೆ.',
      ta: 'மதுரா சாலையில் அதிக துகள்கள் பதிவாகியுள்ளன. பயணிகள் N95 முகக்கவசம் அணிய அறிவுறுத்தப்படுகிறார்கள்.',
      ml: 'മഥുര റോഡിൽ ഉയർന്ന പൊടിപടലങ്ങൾ രേഖപ്പെടുത്തിയിട്ടുണ്ട്. യാത്രക്കാർ N95 മാസ്ക് ധരിക്കുക.',
    },
  },
  {
    ticket_id: 'VAYU-2026-0930-DL-0883',
    timestamp: '2026-09-30T10:04:00Z',
    city_id: 'delhi',
    status: 'AUDIT_VERIFIED',
    classification: 'INDUSTRIAL_STACK_EMISSION',
    statutory_code: 'SRC-03',
    severity_score: 0.92,
    confidence: 0.97,
    location: {
      lat: 28.7120,
      lng: 77.1350,
      address_hint: 'Mayapuri / Narela Conforming Industrial Cluster, Sector C',
      ward_no: 'Ward 04-W',
    },
    reported_by: {
      persona: 'COMMUNITY_DRONE_SURVEILLANCE',
      hash_id: 'DRONE-DL-07',
    },
    weather_context: {
      wind_bearing_deg: 75,
      wind_direction: 'ENE',
      wind_speed_mps: 5.1,
      ambient_temp_c: 31.0,
      atmospheric_stability: 'Class D (Neutral)',
    },
    downwind_exposure_cone: {
      origin: { lat: 28.7120, lng: 77.1350 },
      wind_bearing_deg: 75,
      wind_speed_mps: 5.1,
      dispersion_rate_mps: 2.4,
      cone_angle_deg: 35,
      max_reach_meters: 4100,
      boundary_polygon: [
        { lat: 28.7120, lng: 77.1350 },
        { lat: 28.7280, lng: 77.1620 },
        { lat: 28.7340, lng: 77.1540 },
        { lat: 28.7190, lng: 77.1290 },
        { lat: 28.7120, lng: 77.1350 },
      ],
    },
    impacted_infrastructure: [
      {
        id: 'INFRA-05',
        name: 'ESI Industrial Workers Hospital',
        type: 'HOSPITAL',
        lat: 28.7240,
        lng: 77.1510,
        distance_meters: 1850,
        eta_minutes: 13,
        capacity_beds: 250,
        alert_status: 'EMERGENCY_VENTILATION_LOCK',
      },
    ],
    mitigation_options: [
      {
        action_id: 'ACTION-CEMS-HALT',
        label: 'Direct CEMS Grid Disconnect & Instant Power Derating',
        type: 'ISSUE_NOTICE',
        depot: 'State Pollution Control Board Emergency Cell',
        response_eta_minutes: 2,
        efficacy_rating: 'Immediate Plume Cutoff',
      },
    ],
    visual_markers: [
      'Unscrubbed sulfurous yellow stack plume bypass',
      'Continuous Electrostatic Precipitator (ESP) shutdown signature',
      'Hydrocarbon soot deposition on adjacent buildings',
    ],
    vernacular_advisories: {
      en: 'SEVERE INDUSTRIAL ALERT: Chemical stack bypass detected in Sector C. Keep windows tightly shut. Evacuate adjacent open spaces.',
      hi: 'गंभीर औद्योगिक चेतावनी: सेक्टर सी में रासायनिक उत्सर्जन दर्ज किया गया है। खिड़कियां बंद रखें और खुले क्षेत्रों से दूर रहें।',
      te: 'తీవ్ర పారిశ్రాમિક హెచ్చరిక: సెక్టార్ సిలో రసాయన ఉద్గారాలు గుర్తించబడ్డాయి. కిటికీలు మూసి ఉంచండి.',
      kn: 'ತೀವ್ರ ಕೈಗಾರಿಕಾ ಎಚ್ಚರಿಕೆ: ಸೆಕ್ಟರ್ ಸಿ ಬಳಿ ರಾಸಾಯನಿಕ ಹೊಗೆ ಸೋರಿಕೆ. ಕಿಟಕಿಗಳನ್ನು ಮುಚ್ಚಿಡಿ.',
      ta: 'தீவிர தொழிற்துறை எச்சரிக்கை: செக்டார் சி பகுதியில் ரசாயனப் புகை. ஜன்னல்களை மூடி வைக்கவும்.',
      ml: 'ഗുരുതരമായ വ്യാവസായിക മുന്നറിയിപ്പ്: സെക്ടർ സിയിൽ രാസപ്പുക ചോർച്ച. ജനലുകൾ അടച്ചിടുക.',
    },
  },
];
